Coursework.Web/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace Coursework.Web.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Coursework.Web/Pages/Index.cshtml.cs
using Coursework.Services;
using Coursework.Services.Abstraction;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace Coursework.Web.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        private ICryptoService CryptoService { get; } 

        private IFileService FileService { get; }

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
            CryptoService = new CryptoService();
            FileService = new FileService();
        }
        
        public string FirstTextarea { get; set; }
        
        public string SecondTextarea { get; set; }
       

        public void OnPostStart(string resultDec, string key, int eventHandling)
        {
            try
            {
                if(eventHandling == 0)
                {
                    SecondTextarea = CryptoService.DecodeText(resultDec, key);
                }
                else
                {
                    SecondTextarea = CryptoService.EncodeText(resultDec, key);
                }
            }
            catch
            {
                SecondTextarea = "Ошибка!\nВведите текст!";
            }
        }
        public void OnPostOpenFile(string fileOpen)
        {
            try
            {
                FirstTextarea = FileService.OpenFile(fileOpen);
            }
            catch
            {
                FirstTextarea = "Файл ненайден!";
            }
        }

        public void OnPostRadio(string resultDec, string resultEnc)
        {
            if (string.IsNullOrEmpty(resultDec))
            {
                SecondTextarea = resultDec;
                FirstTextarea = resultEnc;
            }
            else
            {
                SecondTextarea = resultDec;
                FirstTextarea = resultEnc;
            }
        }
    }
}

Coursework.Web/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Курсовой проект";
}

<div class="text-center">
    <h1 class="display-4">Курсовой проект</h1>
    <p>@ViewData["TimeStamp"]</p>
    <form method="post">
        <table>
            <tr>
                <td colspan="3"><input type="text" name="key" placeholder="Ключ" value="скорпион" required autocomplete="off" /></td>
                <td></td>
            </tr>
            <tr>
                <td>
                    <h3>Исходный текст</h3>
                    <input name="fileOpen" type="file" accept=".docx" /><input type="submit" value="Добавить" asp-page-handler="OpenFile" />
                </td>
                <td></td>
                <td>
                    <h3>Результат преобразования</h3>
                </td>
            </tr>
            <tr>
                <td><textarea name="resultDec" placeholder="Исходный текст">@Model.FirstTextarea</textarea></td>
                <td>
                    <p><input type="submit" value="Поменять" asp-page-handler="Radio" /></p>
                    <p><input type="radio" value="0" name="eventHandling" checked />Зашифровать</p>
                    <p><input type="radio" value="1" name="eventHandling" />Расшифровать</p>
                    <p><input type="submit" value="Выполнить" asp-page-handler="Start" /></p>
                </td>
                <td><textarea name="resultEnc" placeholder="Результат преобразования">@Model.SecondTextarea</textarea></td>
            </tr>
        </table>
    </form>
</div>

Coursework.Web/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Course</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">Course</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - Course - Захарова Татьяна</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>